remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Vladimir Cicovic homepage
tagline: hack, code, sleep, repeat
description: Vladimir Cicovic Homepage
url: 'https://vladimir-cicovic.github.io'
